### ISSUE TITLE
Не работает получение сделок с дополнительным условием

### ISSUE THREAD

**Issue by style0092** [ufee/amoapi#12]
$lead = $amo->leads()->where('key', $val)->recursiveCall();
из примера не работает, пытаюсь сделать выборку по status_id, выдает всё равно абсолютно все сделки, пробовал даже по name, все равно не получается.

$lead = $amo->leads()->where('name', $name)->recursiveCall(); //выгружает все сделки
$lead = $amo->leads()->where('status_id', $idstatus)->recursiveCall(); //выгружает все сделки

$lead = $amo->leads()->where('id', $id)->recursiveCall(); //выгружает нужную сделку
этот код аналогичен $lead = $amo->leads()->find($id);, который тоже успешно выполняется.

Не понятно почему так происходит если вот по доп.полям выборка хорошо работает и выгружает только то, что подпадает под выборку.
$leads = $amo->leads()->searchByCustomField('Москва', 623425); // by CF id

**Comment by ufee** [comment]
![image](https://user-images.githubusercontent.com/28390028/72052398-272ef380-32d6-11ea-8534-58ed33702fe4.png)
Поддерживаются любые из допустимых параметров, список доступен в документации к API amoCRM, ни **status_id**, ни **name** там нет, но есть **status** и **query**.
