### ISSUE TITLE
401 ошибка на новых аккаунтах

### ISSUE THREAD

**Issue by bigperson** [ufee/amoapi#17]
Новые аккаунты выдают 401 ошибку при аутентификации. Api ключ у этих аккаунтов в 2 раза короче по длине.

**Comment by ufee** [comment]
Пока не встречал такого, новые аккаунты у нас имеют обычный api ключ.

**Comment by bigperson** [comment]
Решено. Аккаунты меняют ключ после входа в аккаунт и завершения регистрации
