### ISSUE TITLE
Поддержка OAuth2 аутентификации

### ISSUE THREAD

**Issue by bigperson** [ufee/amoapi#18]
Планируется ли поддержка OAuth2 аутентификации? В ближайшее время возможно закроют доступ по ключам.

**Comment by ufee** [comment]
Планируется, доступ не закроют, лишь ограничат получение новых ключей

**Comment by bigperson** [comment]
@ufee В любом случае для новых аккаунтов использовать библиотеку будет проблематично

**Comment by m4tlch** [comment]
> @ufee В любом случае для новых аккаунтов использовать библиотеку будет проблематично

А почему? В связи с переходом на api v4? Вторая версия ведь не отключается

**Comment by bigperson** [comment]
@m4tlch тут пока нет поддержки oauth2

```php
$amo = \Ufee\Amo\Amoapi::setInstance([
    'id' => 123,
    'domain' => 'testdomain',
    'login' => 'test@login',
    'hash' => 'testhash',
    'zone' => 'com', // default: ru
    'timezone' => 'Europe/London', // default: Europe/Moscow
    'lang' => 'en' // default: ru
]);
```
Вторая версия не отключается, да и первая ещё работает, вопрос в том что нужно библиотеку докрутить на получение токена и добавление его автоматом в headers

Либо пару примеров как использовать совместно с amocrm/oauth2-amocrm

**Comment by m4tlch** [comment]
> @m4tlch тут пока нет поддержки oauth2
> 
> ```
> $amo = \Ufee\Amo\Amoapi::setInstance([
>     'id' => 123,
>     'domain' => 'testdomain',
>     'login' => 'test@login',
>     'hash' => 'testhash',
>     'zone' => 'com', // default: ru
>     'timezone' => 'Europe/London', // default: Europe/Moscow
>     'lang' => 'en' // default: ru
> ]);
> ```
> 
> Вторая версия не отключается, да и первая ещё работает, вопрос в том что нужно библиотеку докрутить на получение токена и добавление его автоматом в headers
> 
> Либо пару примеров как использовать совместно с amocrm/oauth2-amocrm

А, ну это да, сейчас нет поддержки oauth2 и нужно будет прикрутить. Но надеюсь, что мейнтейнер библиотеки добавит такую поддержку(обнадеживал, по крайней мере:)). Но если нет - нужно будет свою писать.

**Comment by bigperson** [comment]
@m4tlch Свою писать точно не нужно. Есть https://github.com/amocrm/amocrm-api-php
А вот форкнуть и добавить пул на поддержку oauth2 можно было бы, если @ufee не сделает раньше.
