### ISSUE TITLE
Ошибка с данными типа Integer

### ISSUE THREAD

**Issue by vasilyevanton24** [ufee/amoapi#19]
Подскажите, пожалуйста.
Использую авторизацию oAuth и пытаюсь создать например контакт через новое API, обращаясь к '/api/v4/contacts', используя функцию произвольного запроса, но возникает ошибка валидации для данных типа Integer. С другими типами данных проблем нет. Как это можно решить? Создание контакта - это просто пример. Мне требуется работать с неразобранным, но эта ошибка повторяется и при создании контакта

// Пример кода
$input['contact'][] = [
	'name' => 'test77',
	'created_at' => time(),
];
$amo->ajax()->post($url = '/api/v4/contacts', $input['contact']);

// Пример ошибки:
{"validation-errors":[{"request_id":"0","errors":[{"code":"InvalidType","path":"created_at","detail":"This value should be of type int."}]}],"title":"Bad Request","type":"https://httpstatus.es/400","status":400,"detail":"Request validation failed"}

**Comment by vasilyevanton24** [comment]
Разобрался в причине ошибки. $amo->ajax()->post отправляет не в json формате. А тогда вопрос. Можно ли создать свой пользовательский запрос в json, чтобы не дорабатывать саму библиотеку?

**Comment by ufee** [comment]
> Разобрался в причине ошибки. $amo->ajax()->post отправляет не в json формате. А тогда вопрос. Можно ли создать свой пользовательский запрос в json, чтобы не дорабатывать саму библиотеку?

Да, верно, необходим json формат.
Библиотека будет доработана, так как методы api/v4 пригодятся.
