### ISSUE TITLE
throw new \Exception('Account not found: '.$account_id);

### ISSUE THREAD

**Issue by bigperson** [ufee/amoapi#20]
Постоянно возникает ошибка Account not found: 4 во время setInstance при протухших ранее доступах.
Помогает только удаление кеша.
Отсюда следует еще одна проблема, нельзя задать путь кеша до вызова setInstance. И нет методов для удаления кеша отдельного инстанса

Trace:
![image](https://user-images.githubusercontent.com/4757391/85197450-b3176380-b2e9-11ea-96bd-6fce5a8e3480.png)

**Comment by ufee** [comment]
У вас ID аккаунта имеет значение 4 ?

**Comment by ufee** [comment]
Есть вероятность возникновения подобной проблемы при одновременном использовании Amoapi и Oauthapi, так как кеш не был разделен. Будет патч.

**Comment by bigperson** [comment]
@ufee Да, использовалось как раз переключение.
Было бы не плохо вообще отделить механизм кеширования, чтоб можно было использовать любую независимую реализацию PSR-6
