### ISSUE TITLE
Пользовательские поля (критическая ошибка)

### ISSUE THREAD

**Issue by vasilyevanton24** [ufee/amoapi#22]
Подскажите, пожалуйста, как избежать критической ошибки если пользовательское поле не найдено или не найдено значение для этого поля? 

$lead->cf('field_name')->setValue('value1');

Спасибо.

**Comment by ufee** [comment]
Например так:
```
if (($cf = $lead->cf('field_name')) && in_array('value1', (array)$cf->field->enums)) {
    $cf->setValue('value1');
}
```

**Comment by vasilyevanton24** [comment]
А как вы предполагаете, что пользователи всегда должны проверять наличие полей на существование в системе? Почему бы, изначально исключить критические ошибки примерно таким способом:
public function byId($cf_id)
    {   
        if ($this->fields->find('id', $cf_id)->first()) {
            return $this->fields->find('id', $cf_id)->first();
        } else {
            return new \Ufee\Amo\Models\CustomField([]);
        }
    }

Не очень понятно, как работать с вашей библиотекой. Ведь каждый раз проверять поле - это по-моему какая-то порнография) Вроде у вас классная библиотека, но эти мелочи убивают все ее плюсы. Возможно вы поясните правильное ее использование.
