### ISSUE TITLE
Ошибка 401 при вызове fetchAccessToken()

### ISSUE THREAD

**Issue by iSamodurov** [ufee/amoapi#26]
Получаю следующую ошибку при попытке авторизоваться.
```
{
"title": "Некорректный клиент",
"type": "https://developers.amocrm.ru/v3/errors/OAuthProblemJson",
"status": 401,
"detail": "Авторизация клиента не прошла"
}
```

Шаги:
1. Получаю ссылку для авторизации так $amo->getOauthUrl($arg = ['mode' => 'popup', 'state' => 'amoapi']);
2. На стороне amocrm выбираю для какого аккаунта предоставить доступы
3. Далее следует редирект с кодом на сайт, где получаю code из get параметров
4. далее пытаюсь получить accessToken - $amo->fetchAccessToken($code);
В итоге получаю ошибку выше. 

Подскажите, в чем может быть проблема и куда смотреть?

**Comment by ufee** [comment]
Встречается при несоответствии параметров интеграции и передаваемых в объект:
- client_id
- client_secret
- redirect_uri (чаще всего)
