### ISSUE TITLE
Дополнительное поле по его id

### ISSUE THREAD

**Issue by pavelbush** [ufee/amoapi#28]
Не всегда удобно заполнять по названию поля, клиент может название чуть изменить и вся интеграция слетает) Было бы удобно использовать как название, так и айдишник нужного поля

$lead->cf(284441)->setValue($value);

**Comment by ufee** [comment]
Есть такая возможность:
`$lead->cf()->byId(284441)->setValue($value);`

**Comment by pavelbush** [comment]
> Есть такая возможность:
> 
> ```
> $lead->cf()->byId(284441)->setValue($value);  
> $lead->customFields->byId(284441)->setValue($value);
> ```

Спасибо!
